spring:
  application:
    name: "notification-service"
  profiles:
    active: ${active_profile}
  threads:
    virtual:
      enabled: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 12
        max-page-size: 100
server:
  port: ${port}
  servlet:
    context-path: /notification-api
  forward-headers-strategy: framework
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
    include-exception: false
    include-message: always
    include-stacktrace: never
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: "*/*"
eureka:
  client:
    service-url:
      defaultZone: ${eureka_url}
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 60
    eureka-server-read-timeout-seconds: 60
management:
  endpoints:
    web:
      exposure:
        include: info,health
info:
  application:
    metadata:
      name: ${spring.application.name}
      description: Notification Service for Cart
      version: 0.0.1-SNAPSHOT