spring:
  data:
    mongodb:
      uri: ${dev_mongo_uri}

#custom-properties
bearer-authentication:
  keystore:
    location: ${dev_auth_keystore_location}
    passphrase: ${dev_auth_keystore_passphrase}
    key-alias: ${dev_auth_key_alias}