spring:
  datasource:
    authdb:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${prod_authdb_mysql_url}
      username: ${prod_authdb_mysql_username}
      password: ${prod_authdb_mysql_password}
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${prod_authdb_mysql_url}
        username: ${prod_authdb_mysql_username}
        password: ${prod_authdb_mysql_password}
        pool-name: "Hikari Connection Pool [Prod][Auth DB]"
        maximum-pool-size: 10
        minimum-idle: 1
        idle-timeout: 30000
        connection-timeout: 60000
        connection-test-query: "select now();"
    userdb:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${prod_userdb_mysql_url}
      username: ${prod_userdb_mysql_username}
      password: ${prod_userdb_mysql_password}
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${prod_userdb_mysql_url}
        username: ${prod_userdb_mysql_username}
        password: ${prod_userdb_mysql_password}
        pool-name: "Hikari Connection Pool [Prod][User DB]"
        maximum-pool-size: 10
        minimum-idle: 1
        idle-timeout: 30000
        connection-timeout: 60000
        connection-test-query: "select now();"
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        show_sql: false
        
#custom properties
bearer-authentication:
  keystore:
    location: ${prod_auth_keystore_location}
    passphrase: ${prod_auth_keystore_passphrase}
    key-alias: ${prod_auth_key_alias}
    private-key-passphrase: ${prod_auth_private_key_passphrase}
  token:
    access-token-validity: ${prod_access_token_validity}
    refresh-token-validity: ${prod_refresh_token_validity}
    mfa-token-validity: ${prod_mfa_token_validity}